### PR TITLE
Replace SubMenu findDOMNode usage.

### PR DESCRIPTION
**Pull request by dispalt**
I manually verified this all works with story book.  The tests pass, but I am sure it could be more elegant.  Let me know if you have feedback.  This is the follow up to #362

### CODE REVIEW

**Comment by dispalt** [comment]
> This pull request **introduces 2 alerts** when merging [8b67c98](https://github.com/react-component/menu/commit/8b67c9893c85e44a99139d7aa74525aa00b93dd6) into [f9b55d6](https://github.com/react-component/menu/commit/f9b55d60878a0d83ff776ab69b3d633567a2109c) - [view on LGTM.com](https://lgtm.com/projects/g/react-component/menu/rev/pr-0d8f9d7f0bcd314a312e76a733a20dfc81d45d6f)
> 
> **new alerts:**
> 
> * 2 for Unused variable, import, function or class

Fixed and force-pushed.

**Comment by dispalt** [comment]
Let me know if you'd like me to change something, @zombieJ . Thanks!

**Comment by dispalt** [comment]
@zombieJ ping, if you could take a look, I'd be eternally grateful =)

**Comment by anuarml** [comment]
any update on when this will be merged? it would be great it this issue is closed https://github.com/ant-design/ant-design/issues/26136 , thanks!

**Comment by dispalt** [comment]
Hey folks, just a friendly ping, would love some feedback or a merge @afc163

**Comment by yoyo837** [comment]
Please help to check rc-menu@9

**Comment by dispalt** [comment]
Ill give it go!

**Pull request closed without merging**
