### PR TITLE
Update rc-util version to 4.x

### PR DESCRIPTION
**Pull request by ldabiralai**
As far as I can tell there are no breaking changes that affect `rc-menu`

This change can solve some issues where `rc-util` 3.x is required by another module. It solves this: (as long as you don't have any other rc components that use rc-util 3.x) https://github.com/react-component/trigger/issues/34

### CODE REVIEW

**Comment by ldabiralai** [comment]
Could someone take a look at this?

The build failed because of an error when linting, I reran the build and it's passed now:
https://travis-ci.org/react-component/menu/builds/221316668

@yiminghe @afc163

**Comment by paranoidjk** [comment]
Upgrde node version to v6 in travis.yml

**Comment by ldabiralai** [comment]
Fixed & had to lock down version to react 15.4.x otherwise it downloads 15.5.x causing tests to break. Happy to put in a PR to update this to react 15.5.x once this goes in.

**Comment by paranoidjk** [comment]
@ldabiralai 👍

**Pull request merged**
